name: CI
on: [push]
jobs:

  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
    - name: Set up Go 1.20
      uses: actions/setup-go@v5
      with:
        go-version: 1.20.0
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Download dependencies
      run: |
        go mod download

    - name: Test
      run: go test -cover ./... -v
